



/* function so that user's leaves record*/
create function fUserLeaveDetail(@EmployeeId int,@LeaveId int)
returns TABLE
AS
RETURN 
select tLeaves.LeaveType,tEmployeeLeaves.StartDate,
tEmployeeLeaves.EndDate,tEmployeeLeaves.Status from tBalanceAccount 
INNER JOIN
tLeaves ON tLeaves.LeaveId=
tBalanceAccount.LeaveId	
INNER JOIN
tEmployeeLeaves on tBalanceAccount.LeaveId=tEmployeeLeaves.LeaveId 
AND tEmployeeLeaves.EmployeeId=tBalanceAccount.EmployeeId 
where tBalanceAccount.EmployeeId=@EmployeeId AND tEmployeeLeaves.LeaveId=@LeaveId;
 
select * from fUserLeaveDetail(2,2);

/* function for leave details*/
create function fUserLeaveBalance(@EmployeeId int)
returns TABLE
as 
RETURN
select LeaveId,Balance,LeavesTaken,Approved,Pending,Cancelled
from tBalanceAccount where EmployeeId=@EmployeeId ;


select * from fUserLeaveBalance(1);
/* competence manager would be able to see the leaves request generated by members of his team*/
create function fCMLeaveStatus(@ManagerId int)
returns TABLE
as 
RETURN
select EmployeeId,LeaveId,RequestTime,StartDate,EndDate 
from tEmployeeLeaves
where ManagerId=@ManagerId ;

select * from fCMLeaveStatus(3);
/* CM would be able to see pending requests*/
create function fCMLeaveStatusPending(@ManagerId int)

returns TABLE
as 
RETURN
select EmployeeId,LeaveId,RequestTime,StartDate,EndDate 
from tEmployeeLeaves
where ManagerId=@ManagerId AND  Status='pending' ;

select * from fCMLeaveStatusPending(3);
/* CM will see the leaves approved */
create function fCMLeaveStatusApproved(@ManagerId int)

returns TABLE
as 
RETURN
select EmployeeId,LeaveId,RequestTime,StartDate,EndDate 
from tEmployeeLeaves
where ManagerId=@ManagerId AND Status='approved' ;




select * from tBalanceAccount;
select * from tEmployeeLeaves
select * from tLeaves;
select * from Employee;
select * from ProjectTeamDetails;
 



